name: Makefile CI

on:
  push:
    branches: [ "Grass-Unified" ]
  pull_request:
    branches: [ "Grass-Unified" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Make kernel
      run: python build_kernel.py --aosp --target=m21
